<a href="https://colab.research.google.com/github/sidhu2690/CogniXis/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu121


## Scalars in torch

In [3]:
torch.tensor(1)

tensor(1)

In [6]:
torch.tensor(1).shape

torch.Size([])

Since there is no dimensions it is called scalars

## Vectors in torch

In [7]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [12]:
torch.tensor([1,2,3]).size()

torch.Size([3])

In [31]:
torch.tensor([1,2,3]).ndim

1

As you can see here, there is only one dimension (or simply one row).  
The number of dimensions can be simply understood by the number of braces.  
You can also use the function `ndim` to find the dimension of any tensor.


## Matrices or Tensors

In [14]:
a= torch.tensor([[1,2,3],
              [4,5,6]])

In [15]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
a.shape

torch.Size([2, 3])

In [32]:
a.ndim

2

This means that this will produce a matrix/tensor of shape 2 by 3 (2 rows and 3 columns).  
For higher dimensions, we will have a higher number of braces.


Now, we can learn some functions in Torch and how to use them.

In [25]:
torch.rand(3,4), "", torch.randn(3,4)

(tensor([[0.5925, 0.2693, 0.2281, 0.4266],
         [0.1266, 0.5549, 0.7434, 0.8510],
         [0.4577, 0.6621, 0.9934, 0.0978]]),
 '',
 tensor([[ 0.4807, -1.1407, -0.1454, -2.3451],
         [ 0.1992, -0.8318, -1.8336,  0.4050],
         [-1.6917, -0.5209,  0.5799,  1.8670]]))

In [26]:
torch.rand(3,4).shape

torch.Size([3, 4])

In [28]:
torch.randn(3,4, dtype=torch.float32)

torch.float32

In [29]:
torch.randn(3,4).dtype

torch.float32

Using the function `dtype`, you can find the data type of the tensor.  
Additionally, you can specify and change it.


### Some Functions in Torch

In [30]:
torch.tensor(5).item()

5

In [37]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
torch.zeros_like(input=torch.randn(4, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [39]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.ones_like(torch.randn(3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [43]:
torch.arange(1,10), torch.arange(1, 30, 3)

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28]))

### Some important operations in torch

In [46]:
A= torch.tensor([1,2,3,4,5])

In [47]:
torch.mul(A, 5)

tensor([ 5, 10, 15, 20, 25])

In [48]:
torch.add(A, 10)

tensor([11, 12, 13, 14, 15])

In [50]:
B, C = torch.randn(3,4), torch.randn(4,5) # The result of the matrix multiplication should have a shape of (3, 5) since (3, 4) @ (4, 5) ---> (3, 5)

In [51]:
B @ C

tensor([[-2.9730, -0.8151,  0.1334, -2.1501, -0.6281],
        [-3.4214,  0.7609,  0.1306,  2.1011,  1.0495],
        [-1.7720,  0.7600,  0.9274,  2.7255,  1.2716]])

In [52]:
torch.matmul(B,C)

tensor([[-2.9730, -0.8151,  0.1334, -2.1501, -0.6281],
        [-3.4214,  0.7609,  0.1306,  2.1011,  1.0495],
        [-1.7720,  0.7600,  0.9274,  2.7255,  1.2716]])

Both `torch.matmul` and `@` will perform the same matrix multiplication.

In [54]:
D= torch.tensor([[1,2,3],
              [4,5,6]])
D, "", D.T

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 '',
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [55]:
torch.min(D)

tensor(1)

In [56]:
torch.max(D)

tensor(6)

In [58]:
torch.mean(D, dtype=torch.float)

tensor(3.5000)

In [59]:
torch.argmin(D)  # Position of the smallest element

tensor(0)

In [60]:
torch.argmax(D) # Position of the largest element

tensor(5)

In [69]:
A= torch.randn(1,2,1,1,4)
A.shape, A.squeeze().shape, A.unsqueeze(0).shape

(torch.Size([1, 2, 1, 1, 4]),
 torch.Size([2, 4]),
 torch.Size([1, 1, 2, 1, 1, 4]))

 `Squeeze` will remove all the single dimensions, and `unsqueeze` will add an additional single dimension.

In [78]:
A=torch.tensor([1,2,3])
torch.vstack([A,A,A]), "", torch.hstack([A,A,A])

(tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]),
 '',
 tensor([1, 2, 3, 1, 2, 3, 1, 2, 3]))

## Setting seed in torch

In [79]:
torch.manual_seed(42)

In [80]:
device= "cuda" if torch.cuda.is_available() else "cpu"